# Site settings
title: Docker Meetups In Bordeaux
#email: your-email@domain.com
description: >
  We promote Docker events in the area of Bordeaux, France
  through the Docker Meetups in Bordeaux group.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dockermeetupsinbordeaux.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  dockermeetupsinbordeaux

# Build settings
markdown: kramdown
